{% set name = "icepaposc" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepaposc-{{ version }}.tar.gz
  sha256: 3e4c9a61445c6e7d0be89ddc398e23108cd536986b2e3c6953bd6757fcaf23a6

build:
  number: 0
  noarch: python
  entry_points:
    - icepaposc = icepaposc.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - icepap
    - numpy
    - pyqt
    - pyqtgraph
    - python >=3.5

test:
  imports:
    - icepaposc
    - icepaposc.custom_widgets
  commands:
    - pip check
    - icepaposc --help
  requires:
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/IcepapOSC
  summary: Python application to monitor and tune IcePAP based systems
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - perhedmax
