{% set name = "icepaposc" %}
{% set version = "0.10.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icepaposc-{{ version }}.tar.gz
  sha256: a3c1723c92a0354ec9c8a08985ca8bd23e7745298523bbd782de6d909483d16d

build:
  number: 1
  noarch: python
  entry_points:
    - icepaposc = icepaposc.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - icepap
    - numpy
    - pyqt
    - pyqtgraph
    - python >={{ python_min }}

test:
  imports:
    - icepaposc
    - icepaposc.custom_widgets
  commands:
    - pip check
    - icepaposc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ALBA-Synchrotron/IcepapOSC
  summary: Python application to monitor and tune IcePAP based systems
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - perhedmax
