{% set name = "icepaposc" %}
{% set version = "0.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepaposc-{{ version }}.tar.gz
  sha256: aa7230d02db291d130eedeaf18103353f43d5e5443ebf4cea1e137254094fef8

build:
  number: 0
  noarch: python
  entry_points:
    - icepaposc = icepaposc.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - icepap
    - numpy
    - pyqt
    - pyqtgraph
    - python >=3.5

test:
  imports:
    - icepaposc
    - icepaposc.custom_widgets
  commands:
    - pip check
    - icepaposc --help
  requires:
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/IcepapOSC
  summary: Python application to monitor and tune IcePAP based systems
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - perhedmax
