schema_version: 1

context:
  name: icepaposc
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/icepaposc-${{ version }}.tar.gz
  sha256: 61a8b08056f9b769216ecf0982e427701db8ec12e1c82bccf5b51ab399811330

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - icepaposc = icepaposc.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - icepap >=3.6.1
    - numpy
    - pyqt6
    - pyqtgraph
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - icepaposc
        - icepaposc.custom_widgets
      python_version: ["${{ python_min }}.*", "3.*"]
      pip_check: true
  - script:
      - icepaposc --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Python application to monitor and tune IcePAP based systems
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/icepap-organization/IcepapOSC

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - perhedmax
