schema_version: 1

context:
  name: icepaposc
  version: "0.11.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/icepaposc-${{ version }}.tar.gz
  sha256: b6e996b748883c3c33bad8bac48e666cc89d035bbb5de88251827525fe6e25d7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - icepaposc = icepaposc.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - icepap
    - numpy
    - pyqt
    - pyqtgraph
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - icepaposc
        - icepaposc.custom_widgets
      python_version: ["${{ python_min }}.*", "3.*"]
      pip_check: true
  - script:
      - icepaposc --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Python application to monitor and tune IcePAP based systems
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/icepap-organization/IcepapOSC

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
    - perhedmax
